project:
  type: website
  output-dir: docs

website:
  title: "psci3200-final-project-mitovich"
  navbar:
    left:
      - href: index.qmd
        text: Final Project
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

